---
# handlers file for add_check_pm2_proc_monitoring
 - name: restart the nrpe service on servers
   service: name={{"nrpe" if ansible_os_family == "RedHat" else "nagios-nrpe-server"}} state=restarted